config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins

  resources :books, only: [:show]
  resources :authors, only: [:show]
  resources :groups, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'groups#index'

  get '/task1', to: 'groups#task1'
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  layout :layout_by_resource

  def main; end

  def set_variables variables
    variables.each do |key, value|
      instance_variable_set("@#{key}", value)
    end
  end

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end

  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  def task1
    @a = [22, 11, 33, 44, 66, 55]
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.haml
%h1.w-100= "Groups"

= stylesheet_link_tag 'group'

.nav.flex-column.nav-pills.col-lg-2.d-lg-flex.d-none#v-pills-tab(role="tablist" aria-orientation="vertical")
  %a.nav-link.active#v-pills-all-tab(href="#v-pills-all" data-toggle="pill" role="tab" aria-controls="v-pills-all" aria-selected="true")
    All
  - @groups.each do |group|
    %a.nav-link(id="v-pills-#{group.name}-tab" data-toggle="pill" href="#v-pills-#{group.name}" role="tab" aria-controls="v-pills-#{group.name}" aria-selected="false")
      = group.name

.tab-content#v-pills-tabContent.col-lg-10.col-12
  .d-lg-none
    .nav.nav-pills#v-pills-tab(role="tablist")
      %a.nav-link.mobile.active#v-pills-all-tab(href="#v-pills-all" data-toggle="pill" role="tab" aria-controls="v-pills-all" aria-selected="true")
        All
      - @groups.each do |group|
        %a.nav-link.mobile(id="v-pills-#{group.name}-tab" data-toggle="pill" href="#v-pills-#{group.name}" role="tab" aria-controls="v-pills-#{group.name}" aria-selected="false")
          = group.name
  .tab-pane.fade.show.active#v-pills-all(role="tabpanel" aria-labelledby="v-pills-all-tab")
    - @groups.each do |group|
      %h2= group.name
      .d-flex.owl-carousel.owl-theme
        - group.books.each do |book|
          .card
            = link_to image_tag(book.image.url, alt: book.name, class: "card-img-top"), book
            .card-body
              %h5.card-title
                = link_to book.name, book
              %p.card-text= "Authors:"
              %ul
                - book.authors.each do |author|
                  %li.card-text
                    = link_to author.name, author
  - @groups.each do |group|
    .tab-pane.fade(id="v-pills-#{group.name}" role="tabpanel" aria-labelledby="v-pills-#{group.name}-tab")
      %h2= group.name
      .row
        - group.books.each do |book|
          .col-xl-3.col-lg-4.col-md-6
            .card
              = link_to image_tag(book.image.url, alt: book.name, class: "card-img-top"), book
              .card-body
                %h5.card-title
                  = link_to book.name, book
                %p.card-text= "Authors:"
                %ul
                  - book.authors.each do |author|
                    %li.card-text
                      = link_to author.name, author

= javascript_include_tag 'group'

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/groups/task1.html.haml
= content_for :head do
  %title
    Задание 1

= stylesheet_link_tag 'task1'

.w-100

  %h1 Простые задачки

  %ol
    %li В массиве целых чисел поменяйте местами минимальный и максимальный элементы

    - b = @a.min()
    - b_index = @a.index(b)
    - c = @a.max()
    - c_index = @a.index(c)
    - @a[b_index] = c
    - @a[c_index] = b


    %p.attribute
      %b
        Данно:
    %p.property
      @a = [22, 11, 33, 44, 66, 55]

    %p.attribute
      %b
        Решение:

    %p.property
      b = @a.min()
      %br
      b_index = @a.index(b)
      %br
      c = @a.max()
      %br
      c_index = @a.index(c)
      %br
      @a[b_index] = c
      %br
      @a[c_index] = b

    %p.attribute
      %b
        Ответ:
    %p.property
      @a = #{@a}

    %li В массиве целых чисел найти индексы двух наименьших элементов
    %p.attribute
      %b
        Данно:
    %p.property
      @a = #{@a}

    %p.attribute
      %b
        Решение:
    %p.property_2
      @a.min(2).each do |a|
      %p.property_3
        @a.index(a)

    %p.attribute
      %b
        Ответ:
    %p.property
      - @a.min(2).each do |a|
        = @a.index(a)